name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # !! 請確認下面這個路徑和你 repo 的 csproj 路徑一致
      - name: Restore
        run: dotnet restore "src/TestFlowApp/TestFlowApp.csproj"

      - name: Build (Release)
        run: dotnet build "src/TestFlowApp/TestFlowApp.csproj" -c Release --no-restore

      - name: Publish
        run: dotnet publish "src/TestFlowApp/TestFlowApp.csproj" -c Release -o out --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestFlowApp
          path: out/**
