name: Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/TestFlowApp/TestFlowApp.csproj

      - name: Build
        run: dotnet build ./src/TestFlowApp/TestFlowApp.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./tests --no-build --verbosity normal
